# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to='media/screenshot/'),
        ),
    ]
