# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20170513_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='pos_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='pos_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
